# Introducción {#intro}

La Vicerrectoría General desde la Coordinación del SIGA y la Dirección Nacional de Planeación y Estadística han
venido trabajando en la Guía para la cuantificación, medición y seguimiento a la gestión de los procesos, la cual pone a disposición de los líderes de los procesos y sus integrantes, con el fin de proporcionar los lineamientos para realizar una adecuada identificación de los indicadores de gestión y una oportuna medición, monitoreo y análisis de los resultados que les permita tomar decisiones sobre información confiable.

El punto de partida para su correcta aplicación radica en el entendimiento del estado actual de los indicadores
que reporta cada proceso y con base en ello el poder identificar las necesidades de mejora buscando la
generación de valor agregado, es decir procurar que la información resultante le permita al líder mantenerlo
bajo control y mejorarlo continuamente.

De igual forma hay que reconocer que la Universidad viene desarrollando un modelo de gestión de la
información institucional conformado por 4 servicios de información: estadísticas e indicadores, datos abiertos,
intercambio de datos y servicio de analítica e inteligencia institucional, así como 4 componentes transversales como son calidad de los datos, seguridad de los datos y de la información institucional, gobernabilidad de los datos y reconocimiento de los aspectos legales para gestionar los datos.

Pensando en brindar apoyo a los procesos para que se aplique una metodología adecuada al contexto de la
Universidad y que se realice de manera ordenada y estandarizada, se definieron seis (6) fases secuenciales para la formulación y aplicación de los indicadores de gestión en los procesos vigentes, estas son:

1. Entendimiento del proceso e identificación de variables observables y no observables determinantes para la medición, 

2. Diseño de la medición de la gestión de los procesos,

3. Sistematización de los indicadores de gestión, 

4. Medición de los indicadores de gestión de acuerdo con su periodicidad,

5. Análisis de resultados de medición y toma de decisiones, 

6. Presentación de información a partes interesadas.

Con el fin de asegurar la medición de los indicadores de gestión se estableció la creación de una batería por
procesos con cobertura en sus diferentes niveles de aplicación: Nivel Nacional, Sedes, Centros e Institutos, así como los roles y responsabilidades para su gobernabilidad y de esta manera facilitar la consolidación y presentación de los resultados. De igual forma se estableció el esquema de flujo de comunicación con el fin de visualizar la información que permita tener el proceso bajo control.

Para facilitar la transición hacia el nuevo modelo de cuantificación, medición y seguimiento a la gestión, se van a ir incorporando herramientas que faciliten la apropiación de los diferentes conceptos asociados a la medición del desempeño de los procesos. La aplicación de la metodología para la formulación y aplicación de los
indicadores de gestión aportará al mejoramiento continuo, a la transparencia, a la rendición de cuentas y cumplimiento del compromiso ético mostrando con respeto, honestidad y confiabilidad los resultados obtenidos
en la operación de los procesos.

Por otra parte, vale la pena mencionar que el Sistema de Información SoftExpert cuenta con el módulo de
Desempeño que permite la parametrización de las particularidades de los tableros de control por proceso con el fin de sistematizar la totalidad de la información institucional.

Por último, la guía cuenta con dos anexos, el primero expone los lineamientos para facilitar la priorización de
variables determinantes de medición en los procesos; dando preferencia a aquellas evaluadas con calificaciones
ubicadas en los niveles alto y medio, y un segundo anexo que aclara la aplicación y adopción de esta
metodología para los demás sistemas de gestión que conforman el modelo SIGA, teniendo en cuenta sus
particularidades.