# Gestión de cambio

*	**¿Qué cambios se van a introducir?** En el marco del proyecto BPUN 358 2019 – 2021 *“Transformación de la cultura organizacional desde el enfoque de generación de valor”*, Meta 5.1 Elaborar un documento con la metodología para la cuantificación, medición y seguimiento de la gestión de los procesos, la UNAL se ha propuesto rediseñar la guía para la formulación de indicadores de gestión, incorporando herramientas que faciliten la apropiación de los diferentes conceptos asociados a la medición del desempeño de los procesos, al tiempo que los líderes y  gestores puedan poner en práctica el paso a paso para su correcta puesta en marcha.

*	**¿Para qué hacer estos cambios?** La mejora continua es un enfoque que debe incorporarse en la operación de cualquier entidad dispuesta a adaptarse a la realidad de su contexto para garantizar su supervivencia. En este sentido los cambios metodológicos que se den en cuanto a la forma en que se mide el desempeño de sus procesos deben orientarse a la aplicación de herramientas claras y sencillas que contribuyan a la toma de decisiones sobre una base solida de información confiable y oportuna y no solo limitarse al cumplimiento de compromisos normativos o dados por entes de certificación.

* **¿Qué beneficios traerán los cambios propuestos?** La aplicación de una metodología rediseñada para la medición, cuantificación y seguimiento a la gestión de los procesos aportará a la rendición de cuentas promoviendo la transparencia en la gestión institucional, en la medida en que se pueda evidenciar el desempeño de los procesos a través de indicadores que estructuren la información para determinar de manera objetiva si efectivamente se están cumplimiento los objetivos y metas trazados. 

El cambio metodológico busca aportar significado, relevancia y entendimiento a la gestión de los procesos de la UNAL porque permite describir el estado real en que se encuentran en determinado momento, al tiempo que añade un juicio de valor, lo mas objetivo posible, sobre la adecuación de su desempeño para orientar la posterior toma de decisiones y finalmente comunicar a las diversas partes interesadas estos resultados.
